#cloud-config
#ssh_pwauth: no
users:
  - name: yc-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "${ssh_key}"
runcmd:
  - sudo apt-get update
  - sudo apt-get install perl -y
      